//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yara.Servicos.LiberacaoAutomatica.YaraSAP {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://creditocobranca/AtualizaBloqueio", ConfigurationName="YaraSAP.SoapAtualizaBloqueio_Out")]
    public interface SoapAtualizaBloqueio_Out {
        
        // CODEGEN: Generating message contract since the operation SoapAtualizaBloqueio_Out is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Yara.Servicos.LiberacaoAutomatica.YaraSAP.SoapAtualizaBloqueio_OutResponse SoapAtualizaBloqueio_Out(Yara.Servicos.LiberacaoAutomatica.YaraSAP.SoapAtualizaBloqueio_OutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<Yara.Servicos.LiberacaoAutomatica.YaraSAP.SoapAtualizaBloqueio_OutResponse> SoapAtualizaBloqueio_OutAsync(Yara.Servicos.LiberacaoAutomatica.YaraSAP.SoapAtualizaBloqueio_OutRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://creditocobranca/AtualizaBloqueio")]
    public partial class SoapAtualizaBloqueioORDEM_VENDA : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nUM_ORDEM_VENDAField;
        
        private string nUM_ITEMField;
        
        private string nUM_DIVISAO_REMESSAField;
        
        private string dT_DIVISAO_REMESSAField;
        
        private string bLOQUEIOField;
        
        private string qTDE_BLOQUEIOField;
        
        private string uNIDADEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string NUM_ORDEM_VENDA {
            get {
                return this.nUM_ORDEM_VENDAField;
            }
            set {
                this.nUM_ORDEM_VENDAField = value;
                this.RaisePropertyChanged("NUM_ORDEM_VENDA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string NUM_ITEM {
            get {
                return this.nUM_ITEMField;
            }
            set {
                this.nUM_ITEMField = value;
                this.RaisePropertyChanged("NUM_ITEM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string NUM_DIVISAO_REMESSA {
            get {
                return this.nUM_DIVISAO_REMESSAField;
            }
            set {
                this.nUM_DIVISAO_REMESSAField = value;
                this.RaisePropertyChanged("NUM_DIVISAO_REMESSA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string DT_DIVISAO_REMESSA {
            get {
                return this.dT_DIVISAO_REMESSAField;
            }
            set {
                this.dT_DIVISAO_REMESSAField = value;
                this.RaisePropertyChanged("DT_DIVISAO_REMESSA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string BLOQUEIO {
            get {
                return this.bLOQUEIOField;
            }
            set {
                this.bLOQUEIOField = value;
                this.RaisePropertyChanged("BLOQUEIO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string QTDE_BLOQUEIO {
            get {
                return this.qTDE_BLOQUEIOField;
            }
            set {
                this.qTDE_BLOQUEIOField = value;
                this.RaisePropertyChanged("QTDE_BLOQUEIO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string UNIDADE {
            get {
                return this.uNIDADEField;
            }
            set {
                this.uNIDADEField = value;
                this.RaisePropertyChanged("UNIDADE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://creditocobranca/AtualizaBloqueio")]
    public partial class SoapAtualizaBloqueio_RetornoORDEM_VENDA : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nUM_ORDEM_VENDAField;
        
        private string sTATUSField;
        
        private string mENSAGEMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string NUM_ORDEM_VENDA {
            get {
                return this.nUM_ORDEM_VENDAField;
            }
            set {
                this.nUM_ORDEM_VENDAField = value;
                this.RaisePropertyChanged("NUM_ORDEM_VENDA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string STATUS {
            get {
                return this.sTATUSField;
            }
            set {
                this.sTATUSField = value;
                this.RaisePropertyChanged("STATUS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string MENSAGEM {
            get {
                return this.mENSAGEMField;
            }
            set {
                this.mENSAGEMField = value;
                this.RaisePropertyChanged("MENSAGEM");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SoapAtualizaBloqueio_OutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://creditocobranca/AtualizaBloqueio", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ORDEM_VENDA", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Yara.Servicos.LiberacaoAutomatica.YaraSAP.SoapAtualizaBloqueioORDEM_VENDA[] SoapAtualizaBloqueio;
        
        public SoapAtualizaBloqueio_OutRequest() {
        }
        
        public SoapAtualizaBloqueio_OutRequest(Yara.Servicos.LiberacaoAutomatica.YaraSAP.SoapAtualizaBloqueioORDEM_VENDA[] SoapAtualizaBloqueio) {
            this.SoapAtualizaBloqueio = SoapAtualizaBloqueio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SoapAtualizaBloqueio_OutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://creditocobranca/AtualizaBloqueio", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ORDEM_VENDA", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Yara.Servicos.LiberacaoAutomatica.YaraSAP.SoapAtualizaBloqueio_RetornoORDEM_VENDA[] SoapAtualizaBloqueio_Retorno;
        
        public SoapAtualizaBloqueio_OutResponse() {
        }
        
        public SoapAtualizaBloqueio_OutResponse(Yara.Servicos.LiberacaoAutomatica.YaraSAP.SoapAtualizaBloqueio_RetornoORDEM_VENDA[] SoapAtualizaBloqueio_Retorno) {
            this.SoapAtualizaBloqueio_Retorno = SoapAtualizaBloqueio_Retorno;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SoapAtualizaBloqueio_OutChannel : Yara.Servicos.LiberacaoAutomatica.YaraSAP.SoapAtualizaBloqueio_Out, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SoapAtualizaBloqueio_OutClient : System.ServiceModel.ClientBase<Yara.Servicos.LiberacaoAutomatica.YaraSAP.SoapAtualizaBloqueio_Out>, Yara.Servicos.LiberacaoAutomatica.YaraSAP.SoapAtualizaBloqueio_Out {
        
        public SoapAtualizaBloqueio_OutClient() {
        }
        
        public SoapAtualizaBloqueio_OutClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SoapAtualizaBloqueio_OutClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SoapAtualizaBloqueio_OutClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SoapAtualizaBloqueio_OutClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Yara.Servicos.LiberacaoAutomatica.YaraSAP.SoapAtualizaBloqueio_OutResponse Yara.Servicos.LiberacaoAutomatica.YaraSAP.SoapAtualizaBloqueio_Out.SoapAtualizaBloqueio_Out(Yara.Servicos.LiberacaoAutomatica.YaraSAP.SoapAtualizaBloqueio_OutRequest request) {
            return base.Channel.SoapAtualizaBloqueio_Out(request);
        }
        
        public Yara.Servicos.LiberacaoAutomatica.YaraSAP.SoapAtualizaBloqueio_RetornoORDEM_VENDA[] SoapAtualizaBloqueio_Out(Yara.Servicos.LiberacaoAutomatica.YaraSAP.SoapAtualizaBloqueioORDEM_VENDA[] SoapAtualizaBloqueio) {
            Yara.Servicos.LiberacaoAutomatica.YaraSAP.SoapAtualizaBloqueio_OutRequest inValue = new Yara.Servicos.LiberacaoAutomatica.YaraSAP.SoapAtualizaBloqueio_OutRequest();
            inValue.SoapAtualizaBloqueio = SoapAtualizaBloqueio;
            Yara.Servicos.LiberacaoAutomatica.YaraSAP.SoapAtualizaBloqueio_OutResponse retVal = ((Yara.Servicos.LiberacaoAutomatica.YaraSAP.SoapAtualizaBloqueio_Out)(this)).SoapAtualizaBloqueio_Out(inValue);
            return retVal.SoapAtualizaBloqueio_Retorno;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Yara.Servicos.LiberacaoAutomatica.YaraSAP.SoapAtualizaBloqueio_OutResponse> Yara.Servicos.LiberacaoAutomatica.YaraSAP.SoapAtualizaBloqueio_Out.SoapAtualizaBloqueio_OutAsync(Yara.Servicos.LiberacaoAutomatica.YaraSAP.SoapAtualizaBloqueio_OutRequest request) {
            return base.Channel.SoapAtualizaBloqueio_OutAsync(request);
        }
        
        public System.Threading.Tasks.Task<Yara.Servicos.LiberacaoAutomatica.YaraSAP.SoapAtualizaBloqueio_OutResponse> SoapAtualizaBloqueio_OutAsync(Yara.Servicos.LiberacaoAutomatica.YaraSAP.SoapAtualizaBloqueioORDEM_VENDA[] SoapAtualizaBloqueio) {
            Yara.Servicos.LiberacaoAutomatica.YaraSAP.SoapAtualizaBloqueio_OutRequest inValue = new Yara.Servicos.LiberacaoAutomatica.YaraSAP.SoapAtualizaBloqueio_OutRequest();
            inValue.SoapAtualizaBloqueio = SoapAtualizaBloqueio;
            return ((Yara.Servicos.LiberacaoAutomatica.YaraSAP.SoapAtualizaBloqueio_Out)(this)).SoapAtualizaBloqueio_OutAsync(inValue);
        }
    }
}
