//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yara.AppService.RFCSap {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SoapCriaOrdemVenda", Namespace="http://schemas.datacontract.org/2004/07/Yara.Servicos.PortalFinanceiro.YaraServic" +
        "es")]
    [System.SerializableAttribute()]
    public partial class SoapCriaOrdemVenda : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CANAL_DISTRIBUICAOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GARANTIAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Yara.AppService.RFCSap.SapCommOrdemVendaItem ITEMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NUM_ORDEM_VENDAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ORGANIZACAO_VENDAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PAGADORField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SETOR_ATIVIDADEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TIPO_ORDEM_VENDAField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CANAL_DISTRIBUICAO {
            get {
                return this.CANAL_DISTRIBUICAOField;
            }
            set {
                if ((object.ReferenceEquals(this.CANAL_DISTRIBUICAOField, value) != true)) {
                    this.CANAL_DISTRIBUICAOField = value;
                    this.RaisePropertyChanged("CANAL_DISTRIBUICAO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GARANTIA {
            get {
                return this.GARANTIAField;
            }
            set {
                if ((object.ReferenceEquals(this.GARANTIAField, value) != true)) {
                    this.GARANTIAField = value;
                    this.RaisePropertyChanged("GARANTIA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Yara.AppService.RFCSap.SapCommOrdemVendaItem ITEM {
            get {
                return this.ITEMField;
            }
            set {
                if ((object.ReferenceEquals(this.ITEMField, value) != true)) {
                    this.ITEMField = value;
                    this.RaisePropertyChanged("ITEM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NUM_ORDEM_VENDA {
            get {
                return this.NUM_ORDEM_VENDAField;
            }
            set {
                if ((object.ReferenceEquals(this.NUM_ORDEM_VENDAField, value) != true)) {
                    this.NUM_ORDEM_VENDAField = value;
                    this.RaisePropertyChanged("NUM_ORDEM_VENDA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ORGANIZACAO_VENDA {
            get {
                return this.ORGANIZACAO_VENDAField;
            }
            set {
                if ((object.ReferenceEquals(this.ORGANIZACAO_VENDAField, value) != true)) {
                    this.ORGANIZACAO_VENDAField = value;
                    this.RaisePropertyChanged("ORGANIZACAO_VENDA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PAGADOR {
            get {
                return this.PAGADORField;
            }
            set {
                if ((object.ReferenceEquals(this.PAGADORField, value) != true)) {
                    this.PAGADORField = value;
                    this.RaisePropertyChanged("PAGADOR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SETOR_ATIVIDADE {
            get {
                return this.SETOR_ATIVIDADEField;
            }
            set {
                if ((object.ReferenceEquals(this.SETOR_ATIVIDADEField, value) != true)) {
                    this.SETOR_ATIVIDADEField = value;
                    this.RaisePropertyChanged("SETOR_ATIVIDADE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TIPO_ORDEM_VENDA {
            get {
                return this.TIPO_ORDEM_VENDAField;
            }
            set {
                if ((object.ReferenceEquals(this.TIPO_ORDEM_VENDAField, value) != true)) {
                    this.TIPO_ORDEM_VENDAField = value;
                    this.RaisePropertyChanged("TIPO_ORDEM_VENDA");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SapCommOrdemVendaItem", Namespace="http://schemas.datacontract.org/2004/07/Yara.Servicos.PortalFinanceiro.YaraServic" +
        "es")]
    [System.SerializableAttribute()]
    public partial class SapCommOrdemVendaItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BLOQUEIOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string COND_PAGAMENTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CULTURAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DATA_DIVISAO_REMESSAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NUM_DIVISAO_REMESSAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NUM_ITEMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PAGA_RETIRAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QTDE_PENDENTEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UNIDADEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VALOR_PENDENTEField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BLOQUEIO {
            get {
                return this.BLOQUEIOField;
            }
            set {
                if ((object.ReferenceEquals(this.BLOQUEIOField, value) != true)) {
                    this.BLOQUEIOField = value;
                    this.RaisePropertyChanged("BLOQUEIO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string COND_PAGAMENTO {
            get {
                return this.COND_PAGAMENTOField;
            }
            set {
                if ((object.ReferenceEquals(this.COND_PAGAMENTOField, value) != true)) {
                    this.COND_PAGAMENTOField = value;
                    this.RaisePropertyChanged("COND_PAGAMENTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CULTURA {
            get {
                return this.CULTURAField;
            }
            set {
                if ((object.ReferenceEquals(this.CULTURAField, value) != true)) {
                    this.CULTURAField = value;
                    this.RaisePropertyChanged("CULTURA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DATA_DIVISAO_REMESSA {
            get {
                return this.DATA_DIVISAO_REMESSAField;
            }
            set {
                if ((object.ReferenceEquals(this.DATA_DIVISAO_REMESSAField, value) != true)) {
                    this.DATA_DIVISAO_REMESSAField = value;
                    this.RaisePropertyChanged("DATA_DIVISAO_REMESSA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NUM_DIVISAO_REMESSA {
            get {
                return this.NUM_DIVISAO_REMESSAField;
            }
            set {
                if ((object.ReferenceEquals(this.NUM_DIVISAO_REMESSAField, value) != true)) {
                    this.NUM_DIVISAO_REMESSAField = value;
                    this.RaisePropertyChanged("NUM_DIVISAO_REMESSA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NUM_ITEM {
            get {
                return this.NUM_ITEMField;
            }
            set {
                if ((object.ReferenceEquals(this.NUM_ITEMField, value) != true)) {
                    this.NUM_ITEMField = value;
                    this.RaisePropertyChanged("NUM_ITEM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PAGA_RETIRA {
            get {
                return this.PAGA_RETIRAField;
            }
            set {
                if ((object.ReferenceEquals(this.PAGA_RETIRAField, value) != true)) {
                    this.PAGA_RETIRAField = value;
                    this.RaisePropertyChanged("PAGA_RETIRA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QTDE_PENDENTE {
            get {
                return this.QTDE_PENDENTEField;
            }
            set {
                if ((object.ReferenceEquals(this.QTDE_PENDENTEField, value) != true)) {
                    this.QTDE_PENDENTEField = value;
                    this.RaisePropertyChanged("QTDE_PENDENTE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UNIDADE {
            get {
                return this.UNIDADEField;
            }
            set {
                if ((object.ReferenceEquals(this.UNIDADEField, value) != true)) {
                    this.UNIDADEField = value;
                    this.RaisePropertyChanged("UNIDADE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VALOR_PENDENTE {
            get {
                return this.VALOR_PENDENTEField;
            }
            set {
                if ((object.ReferenceEquals(this.VALOR_PENDENTEField, value) != true)) {
                    this.VALOR_PENDENTEField = value;
                    this.RaisePropertyChanged("VALOR_PENDENTE");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SoapCriaOrdemVenda_Retorno", Namespace="http://schemas.datacontract.org/2004/07/Yara.Servicos.PortalFinanceiro.YaraServic" +
        "es")]
    [System.SerializableAttribute()]
    public partial class SoapCriaOrdemVenda_Retorno : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MENSAGEMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NUM_ORDEM_VENDAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string STATUSField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MENSAGEM {
            get {
                return this.MENSAGEMField;
            }
            set {
                if ((object.ReferenceEquals(this.MENSAGEMField, value) != true)) {
                    this.MENSAGEMField = value;
                    this.RaisePropertyChanged("MENSAGEM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NUM_ORDEM_VENDA {
            get {
                return this.NUM_ORDEM_VENDAField;
            }
            set {
                if ((object.ReferenceEquals(this.NUM_ORDEM_VENDAField, value) != true)) {
                    this.NUM_ORDEM_VENDAField = value;
                    this.RaisePropertyChanged("NUM_ORDEM_VENDA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string STATUS {
            get {
                return this.STATUSField;
            }
            set {
                if ((object.ReferenceEquals(this.STATUSField, value) != true)) {
                    this.STATUSField = value;
                    this.RaisePropertyChanged("STATUS");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SoapFixarLimite", Namespace="http://schemas.datacontract.org/2004/07/Yara.Servicos.PortalFinanceiro.YaraServic" +
        "es")]
    [System.SerializableAttribute()]
    public partial class SoapFixarLimite : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BloquearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoPrincipalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] CodigosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValorLimiteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime VigenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string YaraGalvaniField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Bloquear {
            get {
                return this.BloquearField;
            }
            set {
                if ((this.BloquearField.Equals(value) != true)) {
                    this.BloquearField = value;
                    this.RaisePropertyChanged("Bloquear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoPrincipal {
            get {
                return this.CodigoPrincipalField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoPrincipalField, value) != true)) {
                    this.CodigoPrincipalField = value;
                    this.RaisePropertyChanged("CodigoPrincipal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Codigos {
            get {
                return this.CodigosField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigosField, value) != true)) {
                    this.CodigosField = value;
                    this.RaisePropertyChanged("Codigos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ValorLimite {
            get {
                return this.ValorLimiteField;
            }
            set {
                if ((this.ValorLimiteField.Equals(value) != true)) {
                    this.ValorLimiteField = value;
                    this.RaisePropertyChanged("ValorLimite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Vigencia {
            get {
                return this.VigenciaField;
            }
            set {
                if ((this.VigenciaField.Equals(value) != true)) {
                    this.VigenciaField = value;
                    this.RaisePropertyChanged("Vigencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string YaraGalvani {
            get {
                return this.YaraGalvaniField;
            }
            set {
                if ((object.ReferenceEquals(this.YaraGalvaniField, value) != true)) {
                    this.YaraGalvaniField = value;
                    this.RaisePropertyChanged("YaraGalvani");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SoapFixarLimite_Retorno", Namespace="http://schemas.datacontract.org/2004/07/Yara.Servicos.PortalFinanceiro.YaraServic" +
        "es")]
    [System.SerializableAttribute()]
    public partial class SoapFixarLimite_Retorno : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ErroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensagemField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Erro {
            get {
                return this.ErroField;
            }
            set {
                if ((this.ErroField.Equals(value) != true)) {
                    this.ErroField = value;
                    this.RaisePropertyChanged("Erro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensagem {
            get {
                return this.MensagemField;
            }
            set {
                if ((object.ReferenceEquals(this.MensagemField, value) != true)) {
                    this.MensagemField = value;
                    this.RaisePropertyChanged("Mensagem");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SoapProrrogarTitulo", Namespace="http://schemas.datacontract.org/2004/07/Yara.Servicos.PortalFinanceiro.YaraServic" +
        "es")]
    [System.SerializableAttribute()]
    public partial class SoapProrrogarTitulo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AnoExercicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataProrrogadaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LinhaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroDocumentoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AnoExercicio {
            get {
                return this.AnoExercicioField;
            }
            set {
                if ((object.ReferenceEquals(this.AnoExercicioField, value) != true)) {
                    this.AnoExercicioField = value;
                    this.RaisePropertyChanged("AnoExercicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataProrrogada {
            get {
                return this.DataProrrogadaField;
            }
            set {
                if ((this.DataProrrogadaField.Equals(value) != true)) {
                    this.DataProrrogadaField = value;
                    this.RaisePropertyChanged("DataProrrogada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Empresa {
            get {
                return this.EmpresaField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpresaField, value) != true)) {
                    this.EmpresaField = value;
                    this.RaisePropertyChanged("Empresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Linha {
            get {
                return this.LinhaField;
            }
            set {
                if ((object.ReferenceEquals(this.LinhaField, value) != true)) {
                    this.LinhaField = value;
                    this.RaisePropertyChanged("Linha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroDocumento {
            get {
                return this.NumeroDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroDocumentoField, value) != true)) {
                    this.NumeroDocumentoField = value;
                    this.RaisePropertyChanged("NumeroDocumento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SoapProrrogarTitulo_Retorno", Namespace="http://schemas.datacontract.org/2004/07/Yara.Servicos.PortalFinanceiro.YaraServic" +
        "es")]
    [System.SerializableAttribute()]
    public partial class SoapProrrogarTitulo_Retorno : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensagemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RetornoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensagem {
            get {
                return this.MensagemField;
            }
            set {
                if ((object.ReferenceEquals(this.MensagemField, value) != true)) {
                    this.MensagemField = value;
                    this.RaisePropertyChanged("Mensagem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Retorno {
            get {
                return this.RetornoField;
            }
            set {
                if ((object.ReferenceEquals(this.RetornoField, value) != true)) {
                    this.RetornoField = value;
                    this.RaisePropertyChanged("Retorno");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SoapBloquearTitulo", Namespace="http://schemas.datacontract.org/2004/07/Yara.Servicos.PortalFinanceiro.YaraServic" +
        "es")]
    [System.SerializableAttribute()]
    public partial class SoapBloquearTitulo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AnoExercicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LinhaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroDocumentoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AnoExercicio {
            get {
                return this.AnoExercicioField;
            }
            set {
                if ((object.ReferenceEquals(this.AnoExercicioField, value) != true)) {
                    this.AnoExercicioField = value;
                    this.RaisePropertyChanged("AnoExercicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Empresa {
            get {
                return this.EmpresaField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpresaField, value) != true)) {
                    this.EmpresaField = value;
                    this.RaisePropertyChanged("Empresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Linha {
            get {
                return this.LinhaField;
            }
            set {
                if ((object.ReferenceEquals(this.LinhaField, value) != true)) {
                    this.LinhaField = value;
                    this.RaisePropertyChanged("Linha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroDocumento {
            get {
                return this.NumeroDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroDocumentoField, value) != true)) {
                    this.NumeroDocumentoField = value;
                    this.RaisePropertyChanged("NumeroDocumento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SoapBloquearTitulo_Retorno", Namespace="http://schemas.datacontract.org/2004/07/Yara.Servicos.PortalFinanceiro.YaraServic" +
        "es")]
    [System.SerializableAttribute()]
    public partial class SoapBloquearTitulo_Retorno : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensagemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RetornoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensagem {
            get {
                return this.MensagemField;
            }
            set {
                if ((object.ReferenceEquals(this.MensagemField, value) != true)) {
                    this.MensagemField = value;
                    this.RaisePropertyChanged("Mensagem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Retorno {
            get {
                return this.RetornoField;
            }
            set {
                if ((object.ReferenceEquals(this.RetornoField, value) != true)) {
                    this.RetornoField = value;
                    this.RaisePropertyChanged("Retorno");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SoapAbonarTitulo", Namespace="http://schemas.datacontract.org/2004/07/Yara.Servicos.PortalFinanceiro.YaraServic" +
        "es")]
    [System.SerializableAttribute()]
    public partial class SoapAbonarTitulo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AnoExercicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LinhaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroDocumentoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AnoExercicio {
            get {
                return this.AnoExercicioField;
            }
            set {
                if ((object.ReferenceEquals(this.AnoExercicioField, value) != true)) {
                    this.AnoExercicioField = value;
                    this.RaisePropertyChanged("AnoExercicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Conta {
            get {
                return this.ContaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContaField, value) != true)) {
                    this.ContaField = value;
                    this.RaisePropertyChanged("Conta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Empresa {
            get {
                return this.EmpresaField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpresaField, value) != true)) {
                    this.EmpresaField = value;
                    this.RaisePropertyChanged("Empresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Linha {
            get {
                return this.LinhaField;
            }
            set {
                if ((object.ReferenceEquals(this.LinhaField, value) != true)) {
                    this.LinhaField = value;
                    this.RaisePropertyChanged("Linha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroDocumento {
            get {
                return this.NumeroDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroDocumentoField, value) != true)) {
                    this.NumeroDocumentoField = value;
                    this.RaisePropertyChanged("NumeroDocumento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SoapAbonarTitulo_Retorno", Namespace="http://schemas.datacontract.org/2004/07/Yara.Servicos.PortalFinanceiro.YaraServic" +
        "es")]
    [System.SerializableAttribute()]
    public partial class SoapAbonarTitulo_Retorno : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensagemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RetornoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensagem {
            get {
                return this.MensagemField;
            }
            set {
                if ((object.ReferenceEquals(this.MensagemField, value) != true)) {
                    this.MensagemField = value;
                    this.RaisePropertyChanged("Mensagem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Retorno {
            get {
                return this.RetornoField;
            }
            set {
                if ((object.ReferenceEquals(this.RetornoField, value) != true)) {
                    this.RetornoField = value;
                    this.RaisePropertyChanged("Retorno");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://yara.net", ConfigurationName="RFCSap.ISapComm")]
    public interface ISapComm {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://yara.net/ISapComm/OrdemVendaAlterada", ReplyAction="http://yara.net/ISapComm/OrdemVendaAlteradaResponse")]
        Yara.AppService.RFCSap.SoapCriaOrdemVenda_Retorno OrdemVendaAlterada(Yara.AppService.RFCSap.SoapCriaOrdemVenda ORDEM_VENDA);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://yara.net/ISapComm/OrdemVendaAlterada", ReplyAction="http://yara.net/ISapComm/OrdemVendaAlteradaResponse")]
        System.Threading.Tasks.Task<Yara.AppService.RFCSap.SoapCriaOrdemVenda_Retorno> OrdemVendaAlteradaAsync(Yara.AppService.RFCSap.SoapCriaOrdemVenda ORDEM_VENDA);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://yara.net/ISapComm/FixarLimite", ReplyAction="http://yara.net/ISapComm/FixarLimiteResponse")]
        Yara.AppService.RFCSap.SoapFixarLimite_Retorno FixarLimite(Yara.AppService.RFCSap.SoapFixarLimite limite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://yara.net/ISapComm/FixarLimite", ReplyAction="http://yara.net/ISapComm/FixarLimiteResponse")]
        System.Threading.Tasks.Task<Yara.AppService.RFCSap.SoapFixarLimite_Retorno> FixarLimiteAsync(Yara.AppService.RFCSap.SoapFixarLimite limite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://yara.net/ISapComm/ProrrogarTitulo", ReplyAction="http://yara.net/ISapComm/ProrrogarTituloResponse")]
        Yara.AppService.RFCSap.SoapProrrogarTitulo_Retorno ProrrogarTitulo(Yara.AppService.RFCSap.SoapProrrogarTitulo titulo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://yara.net/ISapComm/ProrrogarTitulo", ReplyAction="http://yara.net/ISapComm/ProrrogarTituloResponse")]
        System.Threading.Tasks.Task<Yara.AppService.RFCSap.SoapProrrogarTitulo_Retorno> ProrrogarTituloAsync(Yara.AppService.RFCSap.SoapProrrogarTitulo titulo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://yara.net/ISapComm/BloquearTitulo", ReplyAction="http://yara.net/ISapComm/BloquearTituloResponse")]
        Yara.AppService.RFCSap.SoapBloquearTitulo_Retorno BloquearTitulo(Yara.AppService.RFCSap.SoapBloquearTitulo titulo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://yara.net/ISapComm/BloquearTitulo", ReplyAction="http://yara.net/ISapComm/BloquearTituloResponse")]
        System.Threading.Tasks.Task<Yara.AppService.RFCSap.SoapBloquearTitulo_Retorno> BloquearTituloAsync(Yara.AppService.RFCSap.SoapBloquearTitulo titulo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://yara.net/ISapComm/AbonarTitulo", ReplyAction="http://yara.net/ISapComm/AbonarTituloResponse")]
        Yara.AppService.RFCSap.SoapAbonarTitulo_Retorno AbonarTitulo(Yara.AppService.RFCSap.SoapAbonarTitulo titulo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://yara.net/ISapComm/AbonarTitulo", ReplyAction="http://yara.net/ISapComm/AbonarTituloResponse")]
        System.Threading.Tasks.Task<Yara.AppService.RFCSap.SoapAbonarTitulo_Retorno> AbonarTituloAsync(Yara.AppService.RFCSap.SoapAbonarTitulo titulo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://yara.net/ISapComm/QuantidadeOVPendente", ReplyAction="http://yara.net/ISapComm/QuantidadeOVPendenteResponse")]
        int QuantidadeOVPendente();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://yara.net/ISapComm/QuantidadeOVPendente", ReplyAction="http://yara.net/ISapComm/QuantidadeOVPendenteResponse")]
        System.Threading.Tasks.Task<int> QuantidadeOVPendenteAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://yara.net/ISapComm/TesteConexaoPI", ReplyAction="http://yara.net/ISapComm/TesteConexaoPIResponse")]
        bool TesteConexaoPI();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://yara.net/ISapComm/TesteConexaoPI", ReplyAction="http://yara.net/ISapComm/TesteConexaoPIResponse")]
        System.Threading.Tasks.Task<bool> TesteConexaoPIAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISapCommChannel : Yara.AppService.RFCSap.ISapComm, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SapCommClient : System.ServiceModel.ClientBase<Yara.AppService.RFCSap.ISapComm>, Yara.AppService.RFCSap.ISapComm {
        
        public SapCommClient() {
        }
        
        public SapCommClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SapCommClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SapCommClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SapCommClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Yara.AppService.RFCSap.SoapCriaOrdemVenda_Retorno OrdemVendaAlterada(Yara.AppService.RFCSap.SoapCriaOrdemVenda ORDEM_VENDA) {
            return base.Channel.OrdemVendaAlterada(ORDEM_VENDA);
        }
        
        public System.Threading.Tasks.Task<Yara.AppService.RFCSap.SoapCriaOrdemVenda_Retorno> OrdemVendaAlteradaAsync(Yara.AppService.RFCSap.SoapCriaOrdemVenda ORDEM_VENDA) {
            return base.Channel.OrdemVendaAlteradaAsync(ORDEM_VENDA);
        }
        
        public Yara.AppService.RFCSap.SoapFixarLimite_Retorno FixarLimite(Yara.AppService.RFCSap.SoapFixarLimite limite) {
            return base.Channel.FixarLimite(limite);
        }
        
        public System.Threading.Tasks.Task<Yara.AppService.RFCSap.SoapFixarLimite_Retorno> FixarLimiteAsync(Yara.AppService.RFCSap.SoapFixarLimite limite) {
            return base.Channel.FixarLimiteAsync(limite);
        }
        
        public Yara.AppService.RFCSap.SoapProrrogarTitulo_Retorno ProrrogarTitulo(Yara.AppService.RFCSap.SoapProrrogarTitulo titulo) {
            return base.Channel.ProrrogarTitulo(titulo);
        }
        
        public System.Threading.Tasks.Task<Yara.AppService.RFCSap.SoapProrrogarTitulo_Retorno> ProrrogarTituloAsync(Yara.AppService.RFCSap.SoapProrrogarTitulo titulo) {
            return base.Channel.ProrrogarTituloAsync(titulo);
        }
        
        public Yara.AppService.RFCSap.SoapBloquearTitulo_Retorno BloquearTitulo(Yara.AppService.RFCSap.SoapBloquearTitulo titulo) {
            return base.Channel.BloquearTitulo(titulo);
        }
        
        public System.Threading.Tasks.Task<Yara.AppService.RFCSap.SoapBloquearTitulo_Retorno> BloquearTituloAsync(Yara.AppService.RFCSap.SoapBloquearTitulo titulo) {
            return base.Channel.BloquearTituloAsync(titulo);
        }
        
        public Yara.AppService.RFCSap.SoapAbonarTitulo_Retorno AbonarTitulo(Yara.AppService.RFCSap.SoapAbonarTitulo titulo) {
            return base.Channel.AbonarTitulo(titulo);
        }
        
        public System.Threading.Tasks.Task<Yara.AppService.RFCSap.SoapAbonarTitulo_Retorno> AbonarTituloAsync(Yara.AppService.RFCSap.SoapAbonarTitulo titulo) {
            return base.Channel.AbonarTituloAsync(titulo);
        }
        
        public int QuantidadeOVPendente() {
            return base.Channel.QuantidadeOVPendente();
        }
        
        public System.Threading.Tasks.Task<int> QuantidadeOVPendenteAsync() {
            return base.Channel.QuantidadeOVPendenteAsync();
        }
        
        public bool TesteConexaoPI() {
            return base.Channel.TesteConexaoPI();
        }
        
        public System.Threading.Tasks.Task<bool> TesteConexaoPIAsync() {
            return base.Channel.TesteConexaoPIAsync();
        }
    }
}
