using System;
using Yara.Domain.Repository.Procedures;

namespace Yara.Domain.Repository
{
    public interface IUnitOfWork : IDisposable
    {
        IRepositoryLog LogRepository { get; }
        IRepositoryGrupo GrupoRepository { get; }
        IRepositoryPermissao PermissaoRepository { get; }
        IRepositoryUsuario UsuarioRepository { get; }
        IRepositorySegmento SegmentoRepository { get; }
        IRepositoryTipoCliente TipoClienteRepository { get; }
        IRepositoryContaClienteComentario ContaClienteComentarioRepository { get; }
        IRepositoryContaCliente ContaClienteRepository { get; }
        IRepositoryContaClienteFinanceiro ContaClienteFinanceiroRepository { get; }
        IRepositoryConceitoCobranca ConceitoCobrancaRepository { get; }
        IRepositoryContaClienteCodigo ContaClienteCodigoRepository { get; }
        IRepositoryContaClienteTelefone ContaClienteTelefoneRepository { get; }
        IRepositoryExperiencia ExperienciaRepository { get; }
        IRepositoryCultura CulturaRepository { get; }
        IRepositoryReceita ReceitaRepository { get; }
        IRepositoryTipoEmpresa TipoEmpresaRepository { get; }
        IRepositoryTipoGarantia TipoGarantiaRepository { get; }
        IRepositoryAreaIrrigada AreaIrrigadaRepository { get; }
        IRepositoryProdutoServico ProdutoServicoRepository { get; }
        IRepositoryIdadeMediaCanavial IdateIdadeMediaCanavialRepository { get; }
        IRepositoryPorcentagemQuebra PorcentagemQuebraRepository { get; }
        IRepositoryProdutividadeMedia ProdutividadeMediaRepository { get; }
        IRepositoryRegiao RegiaoRepository { get; }
        IRepositoryCustoHaRegiao CustoHaRegiaoRepository { get; }
        IRepositoryMediaSaca MediaSacaRepository { get; }
        IRepositoryTipoPecuaria TipoPecuariaRepository { get; }
        IRepositoryFeriado FeriadoRepository { get; }
        IRepositoryEstruturaComercial EstruturaComercialRepository { get; }
        IRepositoryEstruturaComercialPapel EstruturaComercialPapelRepository { get; }
        IRepositoryParametroSistema ParametroSistemaRepository { get; }
        IRepositoryTipoEndividamento TipoEndividamentoRepository { get; }
        IRepositoryAnexo AnexoRepository { get; }
        IRepositoryFluxoLiberacaoManual FluxoLimiteCreditoRepository { get; }
        IRepositoryFerias FeriasRepository { get; }
        IRepositoryOrdemVenda OrdemVendaRepository { get; }
        IRepositoryPropostaLC PropostaLCRepository { get; }
        IRepositoryPropostaLCParceriaAgricola PropostaLCParceriaAgricolaRepository { get; }
        IRepositoryPropostaLCGarantia PropostaLCGarantiaRepository { get; }
        IRepositoryPropostaLCCultura PropostaLCCulturaRepository { get; }
        IRepositoryPropostaLCNecessidadeProduto PropostaLCNecessidadeProdutoRepository { get; }
        IRepositoryPropostaLCMercado PropostaLCMercadoRepository { get; }
        IRepositoryPropostaLCPecuaria PropostaLCPecuariaRepository { get; }
        IRepositoryPropostaLCOutraReceita PropostaLCOutraReceitaRepository { get; }
        IRepositoryPropostaLCReferencia PropostaLCReferenciaRepository { get; }
        IRepositoryPropostaLCBemRural PropostaLCBemRuralRepository { get; }
        IRepositoryPropostaLCBemUrbano PropostaLCBemUrbanoRepository { get; }
        IRepositoryPropostaLCMaquinaEquipamento PropostaLCMaquinaEquipamentoRepository { get; }
        IRepositoryPropostaLCPrecoPorRegiao PropostaLCPrecoPorRegiaoRepository { get; }
        IRepositoryPropostaLCTipoEndividamento PropostaLCTipoEndividamentoRepository { get; }
        IRepositoryPropostaLCDemonstrativo PropostaLCDemonstrativoRepository { get; }
        IRepositoryOrigemRecurso OrigemRecursoRepository { get; }
        IRepositoryStatusCobranca StatusCobrancaRepository { get; }
        IRepositoryCobrancaResultado CobrancaResultadoRepository { get; }
        IRepositoryCidade CidadeRepository { get; }
        IRepositoryEstado EstadoRepository { get; }
        IRepositoryOrdemVendaFluxo OrdemVendaFluxoRepository { get; }
        IRepositoryDivisaoRemessa DivisaoRemessaRepository { get; }
        IRepositoryAnexoArquivo AnexoArquivoRepository { get; }
        IRepositoryLogDivisaoRemessaLiberacao LogDivisaoRemessaLiberacaoRepository { get; }
        IRepositoryEmpresa EmpresaRepository { get; }
        IRepositoryHistoricoContaCliente HistoricoContaClienteRepository { get; }
        IRepositoryContaClienteEstruturaComercial ContaClienteEstruturaComercialRepository { get; }
        IRepositoryContaClienteRepresentante ContaClienteRepresentanteRepository { get; }
        IRepositoryRepresentante RepresentanteRepository { get; }
        IRepositoryProcessamentoCarteira ProcessamentoCarteiraRepository { get; }
        IRepositoryTipoRelacaoGrupoEconomico TipoRelacaoGrupoEconomicoRepository { get; }
        IRepositoryClassificacaoGrupoEconomico ClassificacaoGrupoEconomicoRepository { get; }
        IRepositoryFluxoGrupoEconomico FluxoGrupoEconomicoRepository { get; }
        IRepositoryLiberacaoGrupoEconomicoFluxo LiberacaoGrupoEconomicoFluxoRepository { get; }
        IRepositoryGrupoEconomicoMembro GrupoEconomicoMembroReporitory { get; }
        IRepositorySolicitanteGrupoEconomico SolicitanteGrupoEconomicoRepository { get; }
        IRepositoryGrupoEconomico GrupoEconomicoReporitory { get; }
        IRepositoryCulturaEstado CulturaEstadoReporitory { get; }
        IRepositoryEstruturaPerfilUsuario EstruturaPerfilUsuarioRepository { get; }
        IRepositoryBuscaGrupoCookpit BuscaGrupoCookpitRepository { get; }
        IRepositoryPerfil PerfilRepository { get; }
        IRepositorySolicitanteSerasa SolicitanteSerasaRepository { get; }
        IRepositoryPendenciaSerasa PendenciaSerasaRepository { get; }
        IRepositoryFluxoLiberacaoLimiteCredito FluxoLiberacaoLimiteCreditoRepository { get; }
        IRepositoryFluxoLiberacaoOrdemVenda FluxoLiberacaoOrdemVendaRepository { get; }
        IRepositoryPropostaLCHistorico PropostaLCHistorico { get; }
        IRepositoryBlog BlogRepository { get; }
        IRepositoryPropostaLCAcompanhamento AcompanhamentoPropostaLCRepository { get; }
        IRepositoryPropostaLCComite PropostaLcComiteRepository { get; }
        IRepositoryPropostaLCStatusComite PropostaLcStatusComiteRepository { get; }
        IRepositoryPropostaLCComiteSolicitante PropostaLCComiteSolicitanteRepository { get; }
        IRepositoryPropostaLCGrupoEconomico PropostaLcGrupoEconomico { get; }
        IRepositoryMotivoAbono MotivoAbonoRepository { get; }
        IRepositoryFluxoLiberacaoAbono FluxoLiberacaoAbonoRepository { get; }
        IRepositoryFluxoLiberacaoProrrogacao FluxoLiberacaoProrrogacaoRepository { get; }
        IRepositoryMotivoProrrogacao MotivoProrrogacaoRepository { get; }
        IRepositoryContaClienteVisita ContaClienteVisitaRepository { get; }
        IRepositoryContaClienteBuscaBens ContaClienteBuscaBensRepository { get; }
        IRepositoryTitulo TituloRepository { get; }
        IRepositoryLiberacaoOrdemVendaFluxo LiberacaoOrdemVendaFluxoRepository { get; }
        IRepositoryStatusOrdemVenda StatusOrdemVendaRepository { get; }
        IRepositoryTituloComentario TituloComentarioRepository { get; }
        IRepositorySolicitanteFluxo SolicitanteFluxoRepository { get; }
        IRepositoryPropostaJuridico PropostaJuridicoRepository { get; }
        IRepositoryPropostaJuridicoHistoricoPagamento PropostaJuridicoHistoricoPagamentoRepository { get; }
        IRepositoryPropostaAbono PropostaAbonoRepository { get; }
        IRepositoryPropostaAbonoTitulo PropostaAbonoTituloRepository { get; }
        IRepositoryPropostaJuridicoTitulo PropostaJuridicoTituloRepository { get; }
        IRepositoryPropostaAbonoComite PropostaAbonoComite { get; }
        IRepositoryBloqueioLiberacaoCarregamento BloqueioLiberacaoCarregamentoRepository { get; }
		IRepositoryPropostaJuridicoGarantia PropostaJuridicoGarantiaRepository { get; }
        IRepositoryAnexoArquivoCobranca AnexoArquivoCobrancaRepository { get; }
        IRepositoryContaClienteGarantia ContaClienteGarantiaRepository { get; }
        IRepositoryContaClienteParticipanteGarantia ContaClienteParticipanteGarantiaRepository { get; }
        IRepositoryContaClienteResponsavelGarantia ContaClienteResponsavelGarantiaRepository { get; }
        IRepositoryPropostaAbonoAcompanhamento PropostaAbonoAcompanhamento { get; }
        IRepositoryPropostaProrrogacao PropostaProrrogacao { get; }
        IRepositoryPropostaProrrogacaoTitulo PropostaProrrogacaoTitulo { get; }
        IRepositoryPropostaProrrogacaoComite PropostaProrrogacaoComite { get; }
        IRepositoryPropostaProrrogacaoParcelamento PropostaProrrogacaoParcelamento { get; }
        IRepositoryPropostaProrrogacaoAcompanhamento PropostaProrrogacaoAcompanhamento { get; }
        IRepositoryPropostaAlcadaComercial PropostaAlcadaComercial { get; }
        IRepositoryPropostaAlcadaComercialCultura PropostaAlcadaComercialCultura { get; }
        IRepositoryPropostaAlcadaComercialDocumento PropostaAlcadaComercialDocumento { get; }
        IRepositoryPropostaAlcadaComercialParceriaAgricola PropostaAlcadaComercialParceriaAgricola{ get; }
        IRepositoryPropostaAlcadaComercialProdutoServico PropostaAlcadaComercialProdutoServico { get; }
        IRepositoryPropostaAlcadaComercialRestricao PropostaAlcadaComercialRestricao { get; }
        IRepositoryPropostaAlcadaComercialAcompanhamento PropostaAlcadaComercialAcompanhamentoRepository { get; }
        IRepositoryRelatorios Relatorios { get; }
        IRepositoryMonitor MonitorRepository { get; }
        IRepositoryFluxoRenovacaoVigenciaLC FluxoRenovacaoVigenciaLCRepository { get; }
        IRepositoryPropostaRenovacaoVigenciaLC PropostaRenovacaoVigenciaLCRepository { get; }
        IRepositoryPropostaRenovacaoVigenciaLCComite PropostaRenovacaoVigenciaLCComiteRepository { get; }
        IRepositoryFluxoLiberacaoLCAdicional FluxoLiberacaoLCAdicionalRepository { get; }
        IRepositoryPropostaLCAdicional PropostaLCAdicionalRepository { get; }
        IRepositoryPropostaLCAdicionalAcompanhamento PropostaLCAdicionalAcompanhamentoRepository { get; }
        IRepositoryPropostaLCAdicionalComite PropostaLCAdicionalComiteRepository { get; }
        IRepositoryPropostaLCAdicionalHistorico PropostaLCAdicionalHistoricoRepository { get; }
        IRepositoryFluxoAlcadaAnalise FluxoAlcadaAnaliseRepository { get; }
        IRepositoryFluxoAlcadaAprovacao FluxoAlcadaAprovacaoRepository { get; }
        IRepositoryTribunalJustica TribunalJusticaRepository { get; }

        IRepositoryNotificacoes NotificacoesRepository { get; }

        bool Commit();
    }
}

