// <auto-generated />
namespace Yara.Data.Tests
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Mudancas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Mudancas));
        
        string IMigrationMetadata.Id
        {
            get { return "201710251131449_Mudancas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
