using System;
using System.Collections.Generic;
using Yara.AppService.Interfaces;

namespace Yara.AppService.IoC
{
    public static class Resolver
    {

        public static Dictionary<Type, Type> GetTypes()
        {
            var ioc = new Dictionary<Type, Type>
            {
                { typeof(IAppServiceAmazonS3), typeof(AppServiceAmazonS3) },
                { typeof(IAppServiceGrupo), typeof(AppServiceGrupo) },
                { typeof(IAppServicePermissao), typeof(AppServicePermissao) },
                { typeof(IAppServiceLog), typeof(AppServiceLog) },
                { typeof(IAppServiceContaClienteCodigo), typeof(AppServiceContaClienteCodigo) },
                { typeof(IAppServiceContaClienteTelefone), typeof(AppServiceContaClienteTelefone) },
                { typeof(IAppServiceUsuario), typeof(AppServiceUsuario) },
                { typeof(IAppServiceSegmento), typeof(AppServiceSegmento) },
                { typeof(IAppServiceTipoCliente), typeof(AppServiceTipoCliente) },
                { typeof(IAppServiceContaCliente), typeof(AppServiceContaCliente) },
                { typeof(IAppServiceConceitoCobranca), typeof(AppServiceConceitoCobranca) },
                { typeof(IAppServiceContaClienteFinanceiro), typeof(AppServiceContaClienteFinanceiro) },
                { typeof(IAppServiceContaClienteComentario), typeof(AppServiceContaClienteComentario) },
                { typeof(IAppServiceExperiencia), typeof(AppServiceExperiencia) },
                { typeof(IAppServiceCultura), typeof(AppServiceCultura) },
                { typeof(IAppServiceReceita), typeof(AppServiceReceita) },
                { typeof(IAppServiceTipoGarantia), typeof(AppServiceTipoGarantia) },
                { typeof(IAppServiceTipoEmpresa), typeof(AppServiceTipoEmpresa) },
                { typeof(IAppServiceIdadeMediaCanavial), typeof(AppServiceIdadeMediaCanavial) },
                { typeof(IAppServiceProdutoServico), typeof(AppServiceProdutoServico) },
                { typeof(IAppServiceAreaIrrigada), typeof(AppServiceAreaIrrigada) },
                { typeof(IAppServiceStatusCobranca), typeof(AppServiceStatusCobranca) },
                { typeof(IAppServiceRegiao), typeof(AppServiceRegiao) },
                { typeof(IAppServiceCustoHaRegiao), typeof(AppServiceCustoHaRegiao) },
                { typeof(IAppServiceProdutividadeMedia), typeof(AppServiceProdutividadeMedia) },
                { typeof(IAppServiceMediaSaca), typeof(AppServiceMediaSaca) },
                { typeof(IAppServiceTipoPecuaria), typeof(AppServiceTipoPecuaria) },
                { typeof(IAppServicePorcentagemQuebra), typeof(AppServicePorcentagemQuebra) },
                { typeof(IAppServiceEstruturaComercial), typeof(AppServiceEstruturaComercial) },
                { typeof(IAppServiceEstruturaComercialPapel), typeof(AppServiceEstruturaComercialPapel) },
                { typeof(IAppServiceFeriado), typeof(AppServiceFeriado) },
                { typeof(IAppServiceParametroSistema), typeof(AppServiceParametroSistema) },
                { typeof(IAppServiceTipoEndividamento), typeof(AppServiceTipoEndividamento) },
                { typeof(IAppServiceAnexo), typeof(AppServiceAnexo) },
                { typeof(IAppServiceFerias), typeof(AppServiceFerias) },
                { typeof(IAppServiceFluxoLiberacaoManual), typeof(AppServiceFluxoLiberacaoManual) },
                { typeof(IAppServiceFluxoLiberacaoOrdemVenda), typeof(AppServiceFluxoLiberacaoOrdemVenda) },
                { typeof(IAppServiceOrdemVenda), typeof(AppServiceOrdemVenda) },
                { typeof(IAppServiceEnvioEmail), typeof(AppServiceEnvioEmail) },
                { typeof(IAppServiceCidade), typeof(AppServiceCidade) },
                { typeof(IAppServiceEstado), typeof(AppServiceEstado) },
                { typeof(IAppServiceDivisaoRemessa), typeof(AppServiceDivisaoRemessa) },
                { typeof(IAppServicePropostaLC), typeof(AppServicePropostaLC) },
                { typeof(IAppServicePropostaLCDemonstrativo), typeof(AppServicePropostaLCDemonstrativo) },
                { typeof(IAppServiceOrdemVendaFluxo), typeof(AppServiceOrdemVendaFluxo) },
                { typeof(IAppServiceAnexoArquivo), typeof(AppServiceAnexoArquivo) },
                { typeof(IAppServiceHistoricoContaCliente), typeof(AppServiceHistoricoContaCliente) },
                { typeof(IAppServiceLogDivisaoRemessaLiberacao), typeof(AppServiceLogDivisaoRemessaLiberacao) },
                { typeof(IAppServiceContaClienteEstruturaComercial), typeof(AppServiceContaClienteEstruturaComercial) },
                { typeof(IAppServiceRepresentante), typeof(AppServiceRepresentante) },
                { typeof(IAppServiceTipoRelacaoGrupoEconomico), typeof(AppServiceTipoRelacaoGrupoEconomico) },
                { typeof(IAppServiceClassificacaoGrupoEconomico), typeof(AppServiceClassificacaoGrupoEconomico) },
                { typeof(IAppServiceLiberacaoGrupoEconomicoFluxo), typeof(AppServiceLiberacaoGrupoEconomicoFluxo) },
                { typeof(IAppServiceFluxoGrupoEconomico), typeof(AppServiceFluxoGrupoEconomico) },
                { typeof(IAppServiceGrupoEconomicoMembros), typeof(AppServiceGrupoEconomicoMembros) },
                { typeof(IAppServiceCulturaEstado), typeof(AppServiceCulturaEstado) },
                { typeof(IAppServiceGrupoEconomico), typeof(AppServiceGrupoEconomico) },
                { typeof(IAppServicePerfil), typeof(AppServicePerfil) },
                { typeof(IAppServiceCookpit), typeof(AppServiceCookpit) },
                { typeof(IAppServiceResumoAnaliseAprovacao), typeof(AppServiceResumoAnaliseAprovacao) },
                { typeof(IAppServiceSerasa), typeof(AppServiceSerasa) },
                { typeof(IAppServiceBlog), typeof(AppServiceBlog) },
                { typeof(IAppServiceEstruturaPerfilUsuario), typeof(AppServiceEstruturaPerfilUsuario) },
                { typeof(IAppServiceContaClienteRepresentante), typeof(AppServiceContaClienteRepresentante) },
                { typeof(IAppServicePropostaLCComite), typeof(AppServicePropostaLCComite) },
                { typeof(IAppServiceFluxoLiberacaoLimiteCredito), typeof(AppServiceFluxoLiberacaoLimiteCredito) },
                { typeof(IAppServiceCobranca), typeof(AppServiceCobranca) },
                { typeof(IAppServiceFluxoLiberacaoAbono), typeof(AppServiceFluxoLiberacaoAbono) },
                { typeof(IAppServiceFluxoLiberacaoProrrogacao), typeof(AppServiceFluxoLiberacaoProrrogacao) },
                { typeof(IAppServiceMotivoAbono), typeof(AppServiceMotivoAbono) },
                { typeof(IAppServiceMotivoProrrogacao), typeof(AppServiceMotivoProrrogacao) },
                { typeof(IAppServiceContaClienteVisita), typeof(AppServiceContaClienteVisita) },
                { typeof(IAppServiceContaClienteBuscaBens), typeof(AppServiceContaClienteBuscaBens) },
                { typeof(IAppServiceTitulo), typeof(AppServiceTitulo) },
                { typeof(IAppServiceTituloComentario), typeof(AppServiceTituloComentario) },
                { typeof(IAppServiceOrigemRecurso), typeof(AppServiceOrigemRecurso) },
                { typeof(IAppServicePropostaJuridicoHistoricoPagamento), typeof(AppServicePropostaJuridicoHistoricoPagamento) },
                { typeof(IAppServicePropostaJuridico), typeof(AppServicePropostaJuridico) },
                { typeof(IAppServicePropostaAbono), typeof(AppServicePropostaAbono) },
                { typeof(IAppServicePropostaJuridicoTitulo), typeof(AppServicePropostaJuridicoTitulo) },
                { typeof(IAppServicePropostaJuridicoGarantia), typeof(AppServicePropostaJuridicoGarantia) },
                { typeof(IAppServiceAnexoArquivoCobranca), typeof(AppServiceAnexoArquivoCobranca) },
                { typeof(IAppServiceContaClienteGarantia), typeof(AppServiceContaClienteGarantia) },
                { typeof(IAppServiceContaClienteResponsavelGarantia), typeof(AppServiceContaClienteResponsavelGarantia) },
                { typeof(IAppServiceContaClienteParticipanteGarantia), typeof(AppServiceContaClienteParticipanteGarantia) },
                { typeof(IAppServicePropostaProrrogacao), typeof(AppServicePropostaProrrogacao) },
                { typeof(IAppServiceRFCSap), typeof(AppServiceRFCSap) },
                { typeof(IAppServicePropostaAlcadaComercial), typeof(AppServicePropostaAlcadaComercial) },
                { typeof(IAppServiceRelatorios), typeof(AppServiceRelatorios) },
                { typeof(IAppServicePropostaAlcadaComercialAcompanhamento), typeof(AppServicePropostaAlcadaComercialAcompanhamento) },
                { typeof(IAppServiceMonitor), typeof(AppServiceMonitor) },
                { typeof(IAppServiceFluxoRenovacaoVigenciaLC), typeof(AppServiceFluxoRenovacaoVigenciaLC) },
                { typeof(IAppServicePropostaRenovacaoVigenciaLC), typeof(AppServicePropostaRenovacaoVigenciaLC) },
                { typeof(IAppServicePropostaRenovacaoVigenciaLCComite), typeof(AppServicePropostaRenovacaoVigenciaLCComite) },
                { typeof(IAppServiceFluxoLiberacaoLCAdicional), typeof(AppServiceFluxoLiberacaoLCAdicional) },
                { typeof(IAppServicePropostaLCAdicional), typeof(AppServicePropostaLCAdicional) },
                { typeof(IAppServicePropostaLCAdicionalComite), typeof(AppServicePropostaLCAdicionalComite) },
                { typeof(IAppServiceFluxoAlcadaAnalise), typeof(AppServiceFluxoAlcadaAnalise) },
                { typeof(IAppServiceFluxoAlcadaAprovacao), typeof(AppServiceFluxoAlcadaAprovacao) },
                { typeof(IAppServiceTribunalJustica), typeof(AppServiceTribunalJustica) },
                { typeof(IAppServiceNotificacoes), typeof(AppServiceNotificacoes) }
            };

            return ioc;
        }

    }
}