//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yara.WebApi.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Yara.WebApi.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código da Conta cliente é obrigatório.
        /// </summary>
        public static string accountclienteID {
            get {
                return ResourceManager.GetString("accountclienteID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area is required.
        /// </summary>
        public static string areaRequired {
            get {
                return ResourceManager.GetString("areaRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change vacation is required.
        /// </summary>
        public static string changeVacation {
            get {
                return ResourceManager.GetString("changeVacation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Comentario de Conceito de Cobrança é obrigatório.
        /// </summary>
        public static string chargesLogMessage {
            get {
                return ResourceManager.GetString("chargesLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Classificação é obrigatória.
        /// </summary>
        public static string classificationValid {
            get {
                return ResourceManager.GetString("classificationValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Code Required.
        /// </summary>
        public static string codePermissionGroupRequired {
            get {
                return ResourceManager.GetString("codePermissionGroupRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission Code Required.
        /// </summary>
        public static string codePermissionRequired {
            get {
                return ResourceManager.GetString("codePermissionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codigo do Grupo Econômico é obrigatório..
        /// </summary>
        public static string codGrupoEconomicoId {
            get {
                return ResourceManager.GetString("codGrupoEconomicoId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name required 2 caracter..
        /// </summary>
        public static string conceptLength {
            get {
                return ResourceManager.GetString("conceptLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apelido é obrigatório.
        /// </summary>
        public static string contaclienteApelido {
            get {
                return ResourceManager.GetString("contaclienteApelido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEP é obrigatório.
        /// </summary>
        public static string contaclienteCEP {
            get {
                return ResourceManager.GetString("contaclienteCEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O CEP deve ter 120 caracteres no máximo..
        /// </summary>
        public static string contaclienteCEP120 {
            get {
                return ResourceManager.GetString("contaclienteCEP120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cidade é obrigatória.
        /// </summary>
        public static string contaclienteCidade {
            get {
                return ResourceManager.GetString("contaclienteCidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Cidade deve ter 120 caracteres no máximo..
        /// </summary>
        public static string contaclienteCidade120 {
            get {
                return ResourceManager.GetString("contaclienteCidade120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A conta cliente é obrigatória..
        /// </summary>
        public static string contaclientecomentarioContaClienteID {
            get {
                return ResourceManager.GetString("contaclientecomentarioContaClienteID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A descrição do comentário é obrigatória..
        /// </summary>
        public static string contaclientecomentarioDescricao {
            get {
                return ResourceManager.GetString("contaclientecomentarioDescricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O comentário deve ter no máximo 255 caracteres..
        /// </summary>
        public static string contaclientecomentarioDescricao255 {
            get {
                return ResourceManager.GetString("contaclientecomentarioDescricao255", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço é obrigatório.
        /// </summary>
        public static string contaclienteEndereco {
            get {
                return ResourceManager.GetString("contaclienteEndereco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O endereço deve ter 120 caracteres no máximo..
        /// </summary>
        public static string contaclienteEndereco120 {
            get {
                return ResourceManager.GetString("contaclienteEndereco120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome é obrigatório.
        /// </summary>
        public static string contaclienteNome {
            get {
                return ResourceManager.GetString("contaclienteNome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome deve ter 120 caracteres no máximo..
        /// </summary>
        public static string contaclienteNome120 {
            get {
                return ResourceManager.GetString("contaclienteNome120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Segment is required..
        /// </summary>
        public static string contaClienteSegmentId {
            get {
                return ResourceManager.GetString("contaClienteSegmentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone é obrigatório.
        /// </summary>
        public static string contaclienteTelefone {
            get {
                return ResourceManager.GetString("contaclienteTelefone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Telefone deve ter 120 caracteres no máximo..
        /// </summary>
        public static string contaclienteTelefone120 {
            get {
                return ResourceManager.GetString("contaclienteTelefone120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClientType is required.
        /// </summary>
        public static string contaclienteTipoClienteID {
            get {
                return ResourceManager.GetString("contaclienteTipoClienteID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O UF deve ter 120 caracteres no máximo..
        /// </summary>
        public static string contaclienteUF120 {
            get {
                return ResourceManager.GetString("contaclienteUF120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado é obrigatório.
        /// </summary>
        public static string contaclineteUF {
            get {
                return ResourceManager.GetString("contaclineteUF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O custo deve ser maior que zero..
        /// </summary>
        public static string CostGreat0 {
            get {
                return ResourceManager.GetString("CostGreat0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost is required.
        /// </summary>
        public static string costRegion {
            get {
                return ResourceManager.GetString("costRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Cultura é obrigatória.
        /// </summary>
        public static string culturevalidation {
            get {
                return ResourceManager.GetString("culturevalidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date is Required.
        /// </summary>
        public static string DateBegin {
            get {
                return ResourceManager.GetString("DateBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date must after Start date.
        /// </summary>
        public static string DateBeginGreaterThanDateEnd {
            get {
                return ResourceManager.GetString("DateBeginGreaterThanDateEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date is Required.
        /// </summary>
        public static string DateEnd {
            get {
                return ResourceManager.GetString("DateEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field date is required.
        /// </summary>
        public static string dateHoliday {
            get {
                return ResourceManager.GetString("dateHoliday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Date is Required.
        /// </summary>
        public static string dateRequired {
            get {
                return ResourceManager.GetString("dateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Inicial da Vigencia do Limite de Crédito é requirido.
        /// </summary>
        public static string dateValidity {
            get {
                return ResourceManager.GetString("dateValidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Final da Vigencia do Limite de Crédito é requirido.
        /// </summary>
        public static string dateValidityEnd {
            get {
                return ResourceManager.GetString("dateValidityEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A descrição não deve ultrapassar os 240 caracteres..
        /// </summary>
        public static string DescriptionMaxLength240 {
            get {
                return ResourceManager.GetString("DescriptionMaxLength240", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Vigência é obrigatória.
        /// </summary>
        public static string endDateProposalRequired {
            get {
                return ResourceManager.GetString("endDateProposalRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu uma exceção ao executar a ação, tente novamente mais tarde..
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Amount is required.
        /// </summary>
        public static string fieldAmountPattern {
            get {
                return ResourceManager.GetString("fieldAmountPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code is required.
        /// </summary>
        public static string fieldCodePattern {
            get {
                return ResourceManager.GetString("fieldCodePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description is required.
        /// </summary>
        public static string fieldDescriptionPattern {
            get {
                return ResourceManager.GetString("fieldDescriptionPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only 10 characters for this field.
        /// </summary>
        public static string fieldLengthPattern10 {
            get {
                return ResourceManager.GetString("fieldLengthPattern10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only 120 characters for this field.
        /// </summary>
        public static string fieldLengthPattern120 {
            get {
                return ResourceManager.GetString("fieldLengthPattern120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only 2 characters for this field.
        /// </summary>
        public static string fieldLengthPattern2 {
            get {
                return ResourceManager.GetString("fieldLengthPattern2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only 24 characters for this field.
        /// </summary>
        public static string fieldLengthPattern24 {
            get {
                return ResourceManager.GetString("fieldLengthPattern24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only 50 characters for this field.
        /// </summary>
        public static string fieldLengthPattern50 {
            get {
                return ResourceManager.GetString("fieldLengthPattern50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Name is required..
        /// </summary>
        public static string fieldNamePattern {
            get {
                return ResourceManager.GetString("fieldNamePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Parecer é obrigatório..
        /// </summary>
        public static string fieldParecer {
            get {
                return ResourceManager.GetString("fieldParecer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Weight is required..
        /// </summary>
        public static string fieldWeightPattern {
            get {
                return ResourceManager.GetString("fieldWeightPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor Até é obrigatório..
        /// </summary>
        public static string flowLimitAte {
            get {
                return ResourceManager.GetString("flowLimitAte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor DE é obrigatório..
        /// </summary>
        public static string flowLimitDe {
            get {
                return ResourceManager.GetString("flowLimitDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nivel é obrigatório..
        /// </summary>
        public static string flowLimitNivel {
            get {
                return ResourceManager.GetString("flowLimitNivel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O flag de Acompanhamento é obrigatório.
        /// </summary>
        public static string followProposalRequired {
            get {
                return ResourceManager.GetString("followProposalRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required..
        /// </summary>
        public static string grupoNome {
            get {
                return ResourceManager.GetString("grupoNome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome deve ter no máximo 120 caracteres..
        /// </summary>
        public static string grupoNome120 {
            get {
                return ResourceManager.GetString("grupoNome120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome é obrigatório..
        /// </summary>
        public static string idademediacanavialNome {
            get {
                return ResourceManager.GetString("idademediacanavialNome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome deve ter no máximo 120 caracteres..
        /// </summary>
        public static string idademediacanavialNome120 {
            get {
                return ResourceManager.GetString("idademediacanavialNome120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor do Limite de Crédito é requerido.
        /// </summary>
        public static string limitValue {
            get {
                return ResourceManager.GetString("limitValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager is required.
        /// </summary>
        public static string ManagerField {
            get {
                return ResourceManager.GetString("ManagerField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Média de Fertilizante é obrigatória.
        /// </summary>
        public static string mediafertilizantevalidation {
            get {
                return ResourceManager.GetString("mediafertilizantevalidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor da Proposta não Permitido.
        /// </summary>
        public static string mustProposal {
            get {
                return ResourceManager.GetString("mustProposal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Name Required.
        /// </summary>
        public static string nameRequired {
            get {
                return ResourceManager.GetString("nameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo Vencimento Obrigatório.
        /// </summary>
        public static string NovoVencimentoValid {
            get {
                return ResourceManager.GetString("NovoVencimentoValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divisão de Remessa atribuída com sucesso.
        /// </summary>
        public static string OrderAttr {
            get {
                return ResourceManager.GetString("OrderAttr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division Order Block success.
        /// </summary>
        public static string OrderBlockSuccess {
            get {
                return ResourceManager.GetString("OrderBlockSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordem Enviada ao fluxo manual com sucesso.
        /// </summary>
        public static string OrderRequestSuccess {
            get {
                return ResourceManager.GetString("OrderRequestSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division Order alow success.
        /// </summary>
        public static string OrderSuccess {
            get {
                return ResourceManager.GetString("OrderSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deve incluir pelo menos 1 titulo para está proposta..
        /// </summary>
        public static string PaymentCount {
            get {
                return ResourceManager.GetString("PaymentCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Porcentagem de Fertilizante é obrigatória.
        /// </summary>
        public static string porcentagemfertilizante {
            get {
                return ResourceManager.GetString("porcentagemfertilizante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A porcentagem de quebra é obrigatória.
        /// </summary>
        public static string porcentagemquebraPorcentagem {
            get {
                return ResourceManager.GetString("porcentagemquebraPorcentagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A porcentagem de quebra deve ser maior que zero e menor ou igual a 100.
        /// </summary>
        public static string porcentagemquebraPorcentagemMaiorqueZeroeMenorouIguala100 {
            get {
                return ResourceManager.GetString("porcentagemquebraPorcentagemMaiorqueZeroeMenorouIguala100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Preço é obrigatório.
        /// </summary>
        public static string PrecoValidation {
            get {
                return ResourceManager.GetString("PrecoValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A produtividade média é obrigatória.
        /// </summary>
        public static string produtividademediavalidation {
            get {
                return ResourceManager.GetString("produtividademediavalidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region is required.
        /// </summary>
        public static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero da Divisão da Remessa é obrigatório.
        /// </summary>
        public static string requesterDivisao {
            get {
                return ResourceManager.GetString("requesterDivisao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id do usuario solicitante é obrigatório.
        /// </summary>
        public static string requesterID {
            get {
                return ResourceManager.GetString("requesterID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero do Item da Ordem de Venda é obrigatório.
        /// </summary>
        public static string requesterItemOrdem {
            get {
                return ResourceManager.GetString("requesterItemOrdem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero da Ordem de Venda é obrigatório.
        /// </summary>
        public static string requesterNumeroOrdem {
            get {
                return ResourceManager.GetString("requesterNumeroOrdem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O parecer é obrigatório.
        /// </summary>
        public static string seemProposalRequired {
            get {
                return ResourceManager.GetString("seemProposalRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description is required.
        /// </summary>
        public static string segmentDescription {
            get {
                return ResourceManager.GetString("segmentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Segment is required.
        /// </summary>
        public static string segmentName {
            get {
                return ResourceManager.GetString("segmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Estado é obrigatório.
        /// </summary>
        public static string statevalidation {
            get {
                return ResourceManager.GetString("statevalidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codigo do bloqueio é obrigatorio.
        /// </summary>
        public static string statusBlockOrder {
            get {
                return ResourceManager.GetString("statusBlockOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero da Ordem de Vendas é obrigatória.
        /// </summary>
        public static string statusNumberOrder {
            get {
                return ResourceManager.GetString("statusNumberOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codigo Cliente é obrigatorio.
        /// </summary>
        public static string statusPagadorOrder {
            get {
                return ResourceManager.GetString("statusPagadorOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status is Required.
        /// </summary>
        public static string statusRequired {
            get {
                return ResourceManager.GetString("statusRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Termo de Validação não foi aceito..
        /// </summary>
        public static string termValidate {
            get {
                return ResourceManager.GetString("termValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome é obrigatório..
        /// </summary>
        public static string tipogarantiaNome {
            get {
                return ResourceManager.GetString("tipogarantiaNome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tipo de garantia deve ter no máximo 120 caracteres..
        /// </summary>
        public static string tipogarantiaNome120 {
            get {
                return ResourceManager.GetString("tipogarantiaNome120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or Password is invalid.
        /// </summary>
        public static string tokenInvalid {
            get {
                return ResourceManager.GetString("tokenInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classification Type is  required.
        /// </summary>
        public static string typeclassification {
            get {
                return ResourceManager.GetString("typeclassification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome é obrigatório.
        /// </summary>
        public static string unidademedidaculturaNome {
            get {
                return ResourceManager.GetString("unidademedidaculturaNome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome deve ter no máximo 120 caracteres..
        /// </summary>
        public static string unidademedidaculturaNome120 {
            get {
                return ResourceManager.GetString("unidademedidaculturaNome120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User email is required.
        /// </summary>
        public static string userEmail {
            get {
                return ResourceManager.GetString("userEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is inactive contact your administrator..
        /// </summary>
        public static string userInactive {
            get {
                return ResourceManager.GetString("userInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User login is required.
        /// </summary>
        public static string userLogin {
            get {
                return ResourceManager.GetString("userLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name is required.
        /// </summary>
        public static string userName {
            get {
                return ResourceManager.GetString("userName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User status is required.
        /// </summary>
        public static string userStatus {
            get {
                return ResourceManager.GetString("userStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User type is required.
        /// </summary>
        public static string userType {
            get {
                return ResourceManager.GetString("userType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is required.
        /// </summary>
        public static string userVacation {
            get {
                return ResourceManager.GetString("userVacation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin date vacation is required.
        /// </summary>
        public static string vacationDateBegin {
            get {
                return ResourceManager.GetString("vacationDateBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date vacation is required.
        /// </summary>
        public static string vacationDateEnd {
            get {
                return ResourceManager.GetString("vacationDateEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deve ter mais de 1 membro para criar um grupo econômico..
        /// </summary>
        public static string validationgroup {
            get {
                return ResourceManager.GetString("validationgroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Valor obrigatório.
        /// </summary>
        public static string valueProposalRequired {
            get {
                return ResourceManager.GetString("valueProposalRequired", resourceCulture);
            }
        }
    }
}
