using System.Collections.Generic;

namespace Yara.Service.Serasa.Common
{
    public static class NaturezaOperacaoAnexoII
    {
        public static Dictionary<string, string> NaturezaAnexoII = new Dictionary<string, string>{
            {"AD","ADIANTAMENTO A DEPOSITANTES - C/C DEVEDORES EM GERAL"},
            {"AG","EMPRÉSTIMOS AGRÍCOLAS E INDUSTRIAIS - FINANCIAMENTOS DE CUSTEIO DE INVESTIMENTOS AGRÍCOLAS E INDUSTRIAIS"},
            {"AR","ARRENDAMENTOS, INCLUSIVE LEASING"},
            {"CA","OPERAÇÕES DE CÂMBIO - OPERAÇÕES E FINANCIAMENTOS DE CÂMBIO EM GERAL"},
            {"CB","CDC OUTROS BENS MÓVEIS"},
            {"CH","ADIANTAMENTO A DEPOSITANTES - CHEQUES SEM FUNDOS ACOLHIDOS"},
            {"CL","CDC VEÍCULOS LEVES"},
            {"CM","CDC MOTOCICLETAS E MOTONETAS"},
            {"CR","IMPEDIDOS PELO BANCO CENTRAL DE OBTENÇÃO DE CRÉDITO RURAL"},
            {"CT","CARTÃO DE CRÉDITO"},
            {"CV","CDC VEÍCULOS PESADOS: TRATORES, ÔNIBUS, CAMINHÕES, BARCOS E AVIÕES"},
            {"C2","CONSÓRCIO VEÍCULOS PESADOS: TRATORES, ÔNIBUS, CAMINHÕES, BARCOS E AVIÕES"},
            {"C3","CONSÓRCIO VEÍCULOS LEVES"},
            {"C4","CONSÓRCIO MOTOCICLETAS E MOTONETAS"},
            {"C5","CONSÓRCIO OUTROS BENS MÓVEIS"},
            {"EC","EMPRÉSTIMOS EM CONTAS - C/C GARANTIDAS, FINANCIAMENTOS DE CAPITAL DE GIRO, PROGRAMAS ESPECIAIS, ETC"},
            {"FI","CRÉDITOS E FINANCIAMENTOS - EMPRÉSTIMOS A PESSOAS FÍSICAS, FINANCIAMENTOS AO CONSUMIDOR FINAL, ETC"},
            {"IM","OPERAÇÕES IMOBILIÁRIAS EM GERAL, INCLUSIVE DE SOCIEDADES DE POUPANÇA"},
            {"IP","DÉBITO IPVA"},
            {"LL","LEASING VEÍCULOS LEVES"},
            {"LM","LEASING MOTOCICLETAS E MOTONETAS"},
            {"LV","LEASING VEÍCULOS PESADOS: TRATORES, ÔNIBUS, CAMINHÕES, BARCOS E AVIÕES"},
            {"OJ","OPERAÇÕES AJUIZADAS"},
            {"OO","OUTRAS OPERAÇÕES - DIVERSAS OPERAÇÕES QUE NÃO SE ENQUADRAM NAS DEMAIS"},
            {"RE","OPERAÇÕES DE REPASSE - OPERAÇÕES 63, FINAME, REINVEST, RECON, PROALCOOL, ETC"},
            {"SR","SEGURO DE RISCO DECORRIDO"},
            {"TD","TÍTULOS DESCONTADOS - DESCONTOS DE DUPLICATAS, PROMISSÓRIAS E OUTROS TÍTULOS"}
        };
    }
}
