// <auto-generated />
namespace Yara.Data.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class StatusCobranca_no_Titulo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StatusCobranca_no_Titulo));
        
        string IMigrationMetadata.Id
        {
            get { return "201711072112479_StatusCobranca_no_Titulo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
