// <auto-generated />
namespace Yara.Data.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddcamposparabasedefixacaodeLCnaproposta : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddcamposparabasedefixacaodeLCnaproposta));
        
        string IMigrationMetadata.Id
        {
            get { return "201710311823543_Add campos para base de fixacao de LC na proposta"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
