// <auto-generated />
namespace Yara.Data.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Exposicao_Deliveries : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Exposicao_Deliveries));
        
        string IMigrationMetadata.Id
        {
            get { return "201712072058115_Exposicao_Deliveries"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
