// <auto-generated />
namespace Yara.Data.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Campos_Serasa_PropostaLC : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Campos_Serasa_PropostaLC));
        
        string IMigrationMetadata.Id
        {
            get { return "201712261600440_Campos_Serasa_PropostaLC"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
