// <auto-generated />
namespace Yara.Data.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class OrdemVendaFluxoEstruturadetabelasV3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OrdemVendaFluxoEstruturadetabelasV3));
        
        string IMigrationMetadata.Id
        {
            get { return "201708171622393_Ordem Venda Fluxo - Estrutura de tabelas V3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
