// <auto-generated />
namespace Yara.Data.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UnidadeMedidaCulturaSiglanãoobrigatória : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UnidadeMedidaCulturaSiglanãoobrigatória));
        
        string IMigrationMetadata.Id
        {
            get { return "201709061926287_Unidade Medida Cultura - Sigla não obrigatória"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
