// <auto-generated />
namespace Yara.Data.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ContaClienteAlteracaodeEstruturapermitindocamposnulosv2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ContaClienteAlteracaodeEstruturapermitindocamposnulosv2));
        
        string IMigrationMetadata.Id
        {
            get { return "201709212151376_ContaCliente - Alteracao de Estrutura permitindo campos nulos v2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
