// <auto-generated />
namespace Yara.Data.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FluxoLimiteCreditoAlteracaocampoEstrutura : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FluxoLimiteCreditoAlteracaocampoEstrutura));
        
        string IMigrationMetadata.Id
        {
            get { return "201708101926111_FluxoLimiteCredito - Alteracao campo Estrutura"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
