// <auto-generated />
namespace Yara.Data.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Origem_Recurso_X : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Origem_Recurso_X));
        
        string IMigrationMetadata.Id
        {
            get { return "201711211242524_Origem_Recurso_X"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
