// <auto-generated />
namespace Yara.Data.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class EstruturadeBuscadeBensdeCliente : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EstruturadeBuscadeBensdeCliente));
        
        string IMigrationMetadata.Id
        {
            get { return "201711202108399_Estrutura de Busca de Bens de Cliente"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
