// <auto-generated />
namespace Yara.Data.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class OrdemdeVendaAlteracaodeestruturav3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OrdemdeVendaAlteracaodeestruturav3));
        
        string IMigrationMetadata.Id
        {
            get { return "201708151531180_Ordem de Venda - Alteracao de estruturav3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
