// <auto-generated />
namespace Yara.Data.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Item_Descricao_e_Bloqueios : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Item_Descricao_e_Bloqueios));
        
        string IMigrationMetadata.Id
        {
            get { return "201710041817018_Item_Descricao_e_Bloqueios"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
