// <auto-generated />
namespace Yara.Data.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Titulo_Com_Empresa_Chave : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Titulo_Com_Empresa_Chave));
        
        string IMigrationMetadata.Id
        {
            get { return "201711221224204_Titulo_Com_Empresa_Chave"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
