// <auto-generated />
namespace Yara.Data.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TipoClienteAddSerasa : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TipoClienteAddSerasa));
        
        string IMigrationMetadata.Id
        {
            get { return "201710121753540_TipoCliente-AddSerasa"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
