// <auto-generated />
namespace Yara.Data.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Novocamponatabelacontaclientegarantia : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Novocamponatabelacontaclientegarantia));
        
        string IMigrationMetadata.Id
        {
            get { return "201712112007067_Novo campo na tabela conta cliente garantia"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
