// <auto-generated />
namespace Yara.Data.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Campos_Proposta_AlcadaID_StatusID : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Campos_Proposta_AlcadaID_StatusID));
        
        string IMigrationMetadata.Id
        {
            get { return "201712101736422_Campos_Proposta_AlcadaID_StatusID"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
