// <auto-generated />
namespace Yara.Data.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Ajustenostatusdapropostajuridica : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Ajustenostatusdapropostajuridica));
        
        string IMigrationMetadata.Id
        {
            get { return "201711271531039_Ajuste no status da proposta juridica"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
