// <auto-generated />
namespace Yara.Data.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Serasa_Sem_Motivo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Serasa_Sem_Motivo));
        
        string IMigrationMetadata.Id
        {
            get { return "201711282037036_Serasa_Sem_Motivo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
