// <auto-generated />
namespace Yara.Data.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DataGarantiaCriacao : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DataGarantiaCriacao));
        
        string IMigrationMetadata.Id
        {
            get { return "201711061822224_DataGarantiaCriacao"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
