// <auto-generated />
namespace Yara.Data.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddnovocamponatabeladePropostaLC : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddnovocamponatabeladePropostaLC));
        
        string IMigrationMetadata.Id
        {
            get { return "201711121737222_Add novo campo na tabela de PropostaLC"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
