// <auto-generated />
namespace Yara.Data.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class YARAFINAN388 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(YARAFINAN388));
        
        string IMigrationMetadata.Id
        {
            get { return "201709051059008_YARAFINAN-388"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
