// <auto-generated />
namespace Yara.Data.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Conversao_OrdemVenda_Dolar : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Conversao_OrdemVenda_Dolar));
        
        string IMigrationMetadata.Id
        {
            get { return "201711011632598_Conversao_OrdemVenda_Dolar"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
