// <auto-generated />
namespace Yara.Data.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Cultura_Nova : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Cultura_Nova));
        
        string IMigrationMetadata.Id
        {
            get { return "201709262154009_Cultura_Nova"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
