// <auto-generated />
namespace Yara.Data.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class OrdemdeVendaFluxodeAprovacao : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OrdemdeVendaFluxodeAprovacao));
        
        string IMigrationMetadata.Id
        {
            get { return "201708161243337_Ordem de Venda - Fluxo de Aprovacao"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
