// <auto-generated />
namespace Yara.Data.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FluxoGrupoEconomicoAdicionadoEstruturadeTabela : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FluxoGrupoEconomicoAdicionadoEstruturadeTabela));
        
        string IMigrationMetadata.Id
        {
            get { return "201709221233372_FluxoGrupoEconomico - Adicionado Estrutura de Tabela"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
