// <auto-generated />
namespace Yara.Data.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ContaClienteAddFlagRestricaoSerasa : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ContaClienteAddFlagRestricaoSerasa));
        
        string IMigrationMetadata.Id
        {
            get { return "201708291827419_Conta Cliente - Add Flag Restricao Serasa"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
