// <auto-generated />
namespace Yara.Data.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PropostaLC_Campo_RatingCliente : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PropostaLC_Campo_RatingCliente));
        
        string IMigrationMetadata.Id
        {
            get { return "201801261305120_PropostaLC_Campo_RatingCliente"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
