// <auto-generated />
namespace Yara.Data.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PropostaRenovacaoVigenciaLC_Fields_Length : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PropostaRenovacaoVigenciaLC_Fields_Length));
        
        string IMigrationMetadata.Id
        {
            get { return "201811271825023_PropostaRenovacaoVigenciaLC_Fields_Length"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
