// <auto-generated />
namespace Yara.Data.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Campo_Comentario_LiberacaoOrdemVendaFluxo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Campo_Comentario_LiberacaoOrdemVendaFluxo));
        
        string IMigrationMetadata.Id
        {
            get { return "201803211731528_Campo_Comentario_LiberacaoOrdemVendaFluxo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
