// <auto-generated />
namespace Yara.Data.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Campo_LCAntesGrupo_GrupoEconomicoMembro : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Campo_LCAntesGrupo_GrupoEconomicoMembro));
        
        string IMigrationMetadata.Id
        {
            get { return "201801291957538_Campo_LCAntesGrupo_GrupoEconomicoMembro"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
