// <auto-generated />
namespace Yara.Data.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CondPagto_No_Titulo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CondPagto_No_Titulo));
        
        string IMigrationMetadata.Id
        {
            get { return "201801121611418_CondPagto_No_Titulo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
