// <auto-generated />
namespace Yara.Data.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Tamanho_Campo_Restricao : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Tamanho_Campo_Restricao));
        
        string IMigrationMetadata.Id
        {
            get { return "202011231742288_Tamanho_Campo_Restricao"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
