// <auto-generated />
namespace Yara.Data.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Alinhamento_Estruturas_QAS : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Alinhamento_Estruturas_QAS));
        
        string IMigrationMetadata.Id
        {
            get { return "202206142138234_Alinhamento_Estruturas_QAS"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
