// <auto-generated />
namespace Yara.Data.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FK_PropostaLCComite_FluxoLiberacaoLimiteCredito : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FK_PropostaLCComite_FluxoLiberacaoLimiteCredito));
        
        string IMigrationMetadata.Id
        {
            get { return "202203042238414_FK_PropostaLCComite_FluxoLiberacaoLimiteCredito"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
